<?php

/**
 * @file media_screencast/media_screencast.module
 *
 * Media: Screencast provides a stream wrapper and formatters for videos provided
 * by Screencast, available at http://screencast.com/.
 *
 * @TODO:
 * Tie in Screencast API.
 * Allow editors to search for videos to display on the browser.
 * Allow editors to put in a screencast username to display on the browser.
 * Allow editors to log in w/ their credentials.
 * Allow editors to upload videos to Screencast.
 */

// A registry of variable_get defaults.
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'media_screencast') . '/includes/media_screencast.variables.inc';

// Hooks and callbacks for integrating with File Entity module for display.
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'media_screencast') . '/includes/media_screencast.formatters.inc';

/**
 * Implements hook_media_internet_providers().
 */
function media_screencast_media_internet_providers() {
  $path = drupal_get_path('module', 'media_screencast');
  return array(
    'MediaInternetScreencastHandler' => array(
      'title' => 'screencast',
      'image' => $path . '/images/stream-screencast.png'
    ),
  );
}

/**
 * Implements hook_stream_wrappers().
 */
function media_screencast_stream_wrappers() {
  return array(
    'screencast' => array(
      'name' => t('Screencast videos'),
      'class' => 'MediaScreencastStreamWrapper',
      'description' => t('Videos provided by Screencast.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function media_screencast_theme($existing, $type, $theme, $path) {
  return array(
    'media_screencast_video' => array(
      'variables' => array('uri' => NULL, 'width' => NULL, 'height' => NULL, 'fullscreen' => NULL),
      'file' => 'media_screencast.theme.inc',
      'path' => $path . '/includes/themes',
      'template' => 'media-screencast-video',
    ),
  );
}

/**
 * Implements hook_media_parse().
 *
 * @todo This hook should be deprecated. Refactor Media module to not call it
 *   any more, since media_internet should be able to automatically route to the
 *   appropriate handler.
 */
function media_screencast_media_parse($embed_code) {
  $handler = new MediaInternetScreencastHandler($embed_code);
  return $handler->parse($embed_code);
}

/**
 * Implements hook_media_format_form_prepare_alter().
 */
function media_screencast_media_format_form_prepare_alter(&$form, &$form_state, $media) {
  $settings = array('autosubmit' => ($media->type == "video"));
  drupal_add_js(array('media_format_form' => $settings), 'setting');
}

/**
 * Implements hook_ctools_plugin_api().
 */
function media_screencast_ctools_plugin_api($owner, $api) {
  static $api_versions = array(
    'file_entity' => array(
      'file_default_displays' => 1,
    ),
  );
  if (isset($api_versions[$owner][$api])) {
    return array('version' => $api_versions[$owner][$api]);
  }
}